name: device_tracking
description: "This is the project for device tracking"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial:
    path: plugins/flutter_bluetooth_serial

  # Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  flutter_native_splash: ^2.4.6

  # for MVC
  stacked: ^3.4.4
  get_it: ^8.0.3
  provider: ^6.1.4

  # System
  shared_preferences: ^2.5.3

  # Firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2

  # More
  permission_handler: ^12.0.0+1

  # Bluetooth
  flutter_reactive_ble: ^5.4.0
  flutter_blue_plus: ^1.35.4

  # Utils
  nb_utils: ^7.1.4
  bot_toast: ^4.1.3
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  share_plus: ^10.1.4
  rxdart: ^0.28.0
  intl: ^0.20.2
  intl_utils: ^2.8.10
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/images/png/
