// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSi3EyiQ7c850I8rpZsAzGOvP_TrhxH88',
    appId: '1:933671776659:web:410509b5cf7114ae04f866',
    messagingSenderId: '933671776659',
    projectId: 'tracking-d2885',
    authDomain: 'tracking-d2885.firebaseapp.com',
    storageBucket: 'tracking-d2885.firebasestorage.app',
    measurementId: 'G-9J449Z41YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkWYTiNbMvkTVtdjwiS1lMen_3QvcqzK0',
    appId: '1:933671776659:android:48a35b42aaccb25204f866',
    messagingSenderId: '933671776659',
    projectId: 'tracking-d2885',
    storageBucket: 'tracking-d2885.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNcZ8DILU9hkn8BMOQHIHQ58fcMoDVA7Y',
    appId: '1:933671776659:ios:40d9ff8f4ab76eae04f866',
    messagingSenderId: '933671776659',
    projectId: 'tracking-d2885',
    storageBucket: 'tracking-d2885.firebasestorage.app',
    iosBundleId: 'com.lub.deviceTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNcZ8DILU9hkn8BMOQHIHQ58fcMoDVA7Y',
    appId: '1:933671776659:ios:40d9ff8f4ab76eae04f866',
    messagingSenderId: '933671776659',
    projectId: 'tracking-d2885',
    storageBucket: 'tracking-d2885.firebasestorage.app',
    iosBundleId: 'com.lub.deviceTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSi3EyiQ7c850I8rpZsAzGOvP_TrhxH88',
    appId: '1:933671776659:web:88e820f1cc4f5dbd04f866',
    messagingSenderId: '933671776659',
    projectId: 'tracking-d2885',
    authDomain: 'tracking-d2885.firebaseapp.com',
    storageBucket: 'tracking-d2885.firebasestorage.app',
    measurementId: 'G-L9JJ8D73NK',
  );
}
